Update search_replace

diff --git a/search_replace b/search_replace
--- a/search_replace
+++ b/search_replace
@@ -39,6 +39,29 @@ cat $ParamFile.tmp  | sed 's/\\/\\\\\\\\/g' | sed 's/\//\\\\\//g' | sed 's/\*/\
 mv $ParamFile.tmp1 $ParamFile.tmp
 FileName=$ParamFile.tmp
 
+while read LINE
+do
+   param_name=`echo $LINE | cut -d'=' -f1 | awk -F\$ '{print $3}'`
+   param_value=`echo  $LINE | cut -d'=' -f2`
+   echo "param_name=$param_name"
+   echo "param_value=$param_value"
+   l=\\$\\$
+   echo "Scanning for the variable $param_name... "
+   for input_file in `find $DESTDIR -type f `
+   do
+       param_count=`grep "\\${$l$param_name$l}" $input_file|wc -l`
+       if [ $param_count -gt 0 ]; then
+           perl -p -i -e "s/\\$\\{$l$param_name$l\\}/$param_value/g" $input_file
+	   if [ $? != 0 ]; then
+	       echo "Unable to replace the parameter in $input_file ...Exiting"
+	       exit
+           fi   
+	   echo "$input_file updated"            
+       fi
+   done
+done < $FileName
+rm $FileName
+echo "Parameter replacement completed"
 
-
+   	
 
